import { Book, BookId } from "@/app/enums";

export const bookNames: Record<BookId, Book> = {
	[BookId.Acts]: Book.Acts,
	[BookId.Colossians]: Book.Colossians,
	[BookId.Corinthians1]: Book.Corinthians1,
	[BookId.Corinthians2]: Book.Corinthians2,
	[BookId.Deuteronomy]: Book.Deuteronomy,
	[BookId.Ephesians]: Book.Ephesians,
	[BookId.Exodus]: Book.Exodus,
	[BookId.Galatians]: Book.Galatians,
	[BookId.Genesis]: Book.Genesis,
	[BookId.Hebrews]: Book.Hebrews,
	[BookId.Hosea]: Book.Hosea,
	[BookId.Isaiah]: Book.Isaiah,
	[BookId.James]: Book.James,
	[BookId.Joel]: Book.Joel,
	[BookId.John]: Book.John,
	[BookId.John1]: Book.John1,
	[BookId.John2]: Book.John2,
	[BookId.John3]: Book.John3,
	[BookId.Jude]: Book.Jude,
	[BookId.Leviticus]: Book.Leviticus,
	[BookId.Luke]: Book.Luke,
	[BookId.Mark]: Book.Mark,
	[BookId.Numbers]: Book.Numbers,
	[BookId.Peter1]: Book.Peter1,
	[BookId.Peter2]: Book.Peter2,
	[BookId.Philemon]: Book.Philemon,
	[BookId.Philippians]: Book.Philippians,
	[BookId.Psalms]: Book.Psalms,
	[BookId.Revelation]: Book.Revelation,
	[BookId.Romans]: Book.Romans,
	[BookId.Samuel1]: Book.Samuel1,
	[BookId.Samuel2]: Book.Samuel2,
	[BookId.Thessalonians1]: Book.Thessalonians1,
	[BookId.Thessalonians2]: Book.Thessalonians2,
	[BookId.Timothy1]: Book.Timothy1,
	[BookId.Timothy2]: Book.Timothy2,
	[BookId.Titus]: Book.Titus,
};
