export enum Book {
	Colossians = "Colossians",
	Corinthians1 = "1 Corinthians",
	Corinthians2 = "2 Corinthians",
	Deuteronomy = "Deuteronomy",
	Ephesians = "Ephesians",
	Exodus = "Exodus",
	Galatians = "Galatians",
	Genesis = "Genesis",
	Isaiah = "Isaiah",
	Leviticus = "Leviticus",
	Luke = "Luke",
	Mark = "Mark",
	Numbers = "Numbers",
	Philippians = "Philippians",
	Psalms = "Psalms",
	Revelation = "Revelation",
	Romans = "Romans",
	Thessalonians1 = "1 Thessalonians",
	Thessalonians2 = "2 Thessalonians",
	Timothy1 = "1 Timothy",
	Timothy2 = "2 Timothy",
}

export enum BookId {
	Colossians = "COL",
	Corinthians1 = "1CO",
	Corinthians2 = "2CO",
	Deuteronomy = "DEU",
	Ephesians = "EPH",
	Exodus = "EXO",
	Galatians = "GAL",
	Genesis = "GEN",
	Isaiah = "ISA",
	Leviticus = "LEV",
	Luke = "LUK",
	Mark = "MRK",
	Numbers = "NUM",
	Philippians = "PHP",
	Psalms = "PSA",
	Revelation = "REV",
	Romans = "ROM",
	Thessalonians1 = "1TH",
	Thessalonians2 = "2TH",
	Timothy1 = "1TI",
	Timothy2 = "2TI",
}
